"use strict";
let isDone = true;
let age = 25;
let firstName = "Komal";
let numbers = [1, 2, 3];
var Color;
(function (Color) {
    Color[Color["Red"] = 0] = "Red";
    Color[Color["Green"] = 1] = "Green";
    Color[Color["Blue"] = 2] = "Blue";
})(Color || (Color = {}));
let inferredString = "Hello Komal";
let inferredNumber = 123;
let inferredBool = false;
let someValue = "I am a string";
let strLength1 = someValue.length;
let strLength2 = someValue.length;
console.log("Primitive Types:");
console.log(`Name: ${firstName}, Age: ${age}, Done: ${isDone}`);
console.log("Numbers:", numbers);
console.log("\nEnum:");
console.log("My Color:", Color.Green);
console.log("\nType Inference:");
console.log("Inferred String:", inferredString);
console.log("Inferred Number:", inferredNumber);
console.log("Inferred Boolean:", inferredBool);
console.log("\nType Assertion:");
console.log("String length (1):", strLength1);
console.log("String length (2):", strLength2);
